"""empty message

Revision ID: 0c40cc04df00
Revises: edd2a993b29e
Create Date: 2026-08-08 09:58:25.494310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c40cc04df00'
down_revision = 'edd2a993b29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('receptionists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id', 'trainer_id')
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id', 'trainer_id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('receptionist_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('workout_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receptionist_id'], ['receptionists.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id', 'trainer_id'], ['workout_plans.id', 'workout_plans.trainer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index('idx_member_plan_trainer', ['workout_plan_id', 'trainer_id'], unique=False)

    op.create_table('workout_plan_exercises',
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id', 'trainer_id'], ['exercises.id', 'exercises.trainer_id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id', 'trainer_id'], ['workout_plans.id', 'workout_plans.trainer_id'], ),
    sa.PrimaryKeyConstraint('workout_plan_id', 'trainer_id', 'exercise_id')
    )
    op.create_table('progress_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('progress_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress_reports')
    op.drop_table('workout_plan_exercises')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index('idx_member_plan_trainer')

    op.drop_table('members')
    op.drop_table('workout_plans')
    op.drop_table('exercises')
    op.drop_table('receptionists')
    op.drop_table('equipments')
    # ### end Alembic commands ###
